# Generated by Django 2.2 on 2019-10-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jist', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=20)),
                ('semester', models.FloatField()),
                ('department', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/')),
                ('roll_no', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
