# Generated by Django 2.2 on 2019-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jist', '0007_auto_20191028_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
